<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-19T00:38:26 PDT" name="Smoke Suite" finished-at="2024-03-19T00:38:32 PDT" duration-ms="6557">
    <groups>
    </groups>
    <test started-at="2024-03-19T00:38:26 PDT" name="Login functionality" finished-at="2024-03-19T00:38:30 PDT" duration-ms="4400">
      <class name="org.techArk.tests.login.ValidateLoginAPI_Functionality">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:org.techArk.tests.login.ValidateLoginAPI_Functionality@19bb07ed]" started-at="2024-03-19T00:38:26 PDT" name="beforeClass" finished-at="2024-03-19T00:38:27 PDT" duration-ms="1011" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="validateLoginWithValidCredentials()[pri:0, instance:org.techArk.tests.login.ValidateLoginAPI_Functionality@19bb07ed]" started-at="2024-03-19T00:38:27 PDT" name="validateLoginWithValidCredentials" description="validate login functionality with valid credentials" finished-at="2024-03-19T00:38:30 PDT" duration-ms="2510" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginWithValidCredentials -->
        <test-method signature="validateLoginWithInValidCredentials()[pri:1, instance:org.techArk.tests.login.ValidateLoginAPI_Functionality@19bb07ed]" started-at="2024-03-19T00:38:30 PDT" name="validateLoginWithInValidCredentials" description="validate login functionality with invalid credentials" finished-at="2024-03-19T00:38:30 PDT" duration-ms="355" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginWithInValidCredentials -->
      </class> <!-- org.techArk.tests.login.ValidateLoginAPI_Functionality -->
    </test> <!-- Login functionality -->
    <test started-at="2024-03-19T00:38:30 PDT" name="Add data and delete data functionality" finished-at="2024-03-19T00:38:32 PDT" duration-ms="1634">
      <class name="org.techArk.tests.CRUD.ValidateAddAndDeleteData_Functionality">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:org.techArk.tests.CRUD.ValidateAddAndDeleteData_Functionality@41fbdac4]" started-at="2024-03-19T00:38:25 PDT" name="beforeSuite" finished-at="2024-03-19T00:38:26 PDT" duration-ms="83" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:org.techArk.tests.CRUD.ValidateAddAndDeleteData_Functionality@41fbdac4]" started-at="2024-03-19T00:38:30 PDT" name="beforeClass" finished-at="2024-03-19T00:38:31 PDT" duration-ms="82" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="validateDeleteData()[pri:2, instance:org.techArk.tests.CRUD.ValidateAddAndDeleteData_Functionality@41fbdac4]" started-at="2024-03-19T00:38:31 PDT" name="validateDeleteData" description="delete repo functionality" finished-at="2024-03-19T00:38:31 PDT" duration-ms="527" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDeleteData -->
        <test-method signature="validateDeletedDataInGetData()[pri:3, instance:org.techArk.tests.CRUD.ValidateAddAndDeleteData_Functionality@41fbdac4]" started-at="2024-03-19T00:38:31 PDT" name="validateDeletedDataInGetData" description="validate deleted repo" finished-at="2024-03-19T00:38:32 PDT" depends-on-methods="org.techArk.tests.CRUD.ValidateAddAndDeleteData_Functionality.validateDeleteData" duration-ms="601" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDeletedDataInGetData -->
        <test-method signature="addrepo()[pri:4, instance:org.techArk.tests.CRUD.ValidateAddAndDeleteData_Functionality@41fbdac4]" started-at="2024-03-19T00:38:32 PDT" name="addrepo" description="Add repo functionality" finished-at="2024-03-19T00:38:32 PDT" duration-ms="399" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Repo is created in github expected [201] but found [422]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Repo is created in github expected [201] but found [422]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.techArk.tests.CRUD.ValidateAddAndDeleteData_Functionality.addrepo(ValidateAddAndDeleteData_Functionality.java:105)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addrepo -->
      </class> <!-- org.techArk.tests.CRUD.ValidateAddAndDeleteData_Functionality -->
    </test> <!-- Add data and delete data functionality -->
  </suite> <!-- Smoke Suite -->
</testng-results>
